language: generic
sudo: required
services: docker

before_install:
  - docker build -t vaspir/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vaspir/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-433202046557"
  on:
    branch: "feature-branch"
  access_key_id: "AKIAWJXG2UZO5JNZTFBT"
  secret_access_key: "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"