language: generic
sudo: required
services: docker

before_install:
  - docker build -t vaspir/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vaspir/react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-433202046557"
  on:
    branch: "master"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"