language: generic
sudo: required
services: docker

before_install:
  - docker build -t vaspir/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vaspir/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "vaspir-docker-react-bucket"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"